name 'redis'
maintainer 'Rob Ferney'
maintainer_email 'rob@ferney.org'
license 'All Rights Reserved'
description 'Installs/Configures redis'
long_description 'Installs/Configures redis'
version '0.1.0'
chef_version '>= 13.0'

issues_url 'https://github.com/coquus-liber/redis/issues'
source_url 'https://github.com/coquus-liber/redis'
